### ISSUE TITLE
Plugin not supported thrown by chrome browser

### ISSUE THREAD

**Issue by Surdok** [Adri-Glez/filepond-plugin-pdf-preview#4]
Hi

I have encountered some error regarding adding this plugin to filepond.

Refused to load the image

![image](https://user-images.githubusercontent.com/24224586/126959014-06b9bde6-cfec-4e5b-9b06-4ccbacd4cead.png)

**Comment by Adri-Glez** [comment]
This error is not related with the plugin, is becouse your page-server security configuration don't let reach the resources. Review the CORS configuration in your server.

**Comment by Surdok** [comment]
Yes this is what I found. 

The type of the attachment that I have provided filepond with was image/pdf, which the browser didn't support. So I have changed it to application/pdf and it worked :)
